### ISSUE TITLE
Is there any way to pass arguments to Drush?

### ISSUE THREAD

**Issue by humansky** [nickpack/grunt-drush#6]
I'm trying to pass arguments to drush based on environment:

```
var drush_opts = '--no-cache';
if(grunt.option('target') == 'prod') {
  drush_opts = ' --working-copy --no-gitinfofile --no-cache';
}

grunt.config('drush', {
    make: {
        args: ['make', '<%= config.srcPaths.make %>', drush_opts],
        dest: '<%= config.buildPaths.html %>'
    }
});
```

But the code above doesn't seem to work. Any idea how I can pass parameters to drush?

**Comment by nickpack** [comment]
@humansky In theory that should work, I haven't done anything with this in a long time so would have to check, but worst case splitting the string by the space should do the trick.

**Comment by humansky** [comment]
@nickpack forgot to close this issue, but it works by throwing all the args in comma separated list:

For example:
```
args: ['make', '<%= config.srcPaths.make %>', '--no-gitinfofile']
```
