### ISSUE TITLE
dest or src property must exist.

### ISSUE THREAD

**Issue by chasingmaxwell** [nickpack/grunt-drush#7]
Either the "dest" or the "src" property is required for this.files to be populated within the multitask (https://github.com/nickpack/grunt-drush/blob/master/tasks/drush.js#L25). So if you do not include one of those two properties, the task will do nothing. I've been including `src: ''`. This is not very intuitive since many drush commands do not perform any actions on files. Is there a better way to parse target configuration to avoid this requirement?

**Comment by IslandUsurper** [comment]
Fixed by #8.

**Comment by nickpack** [comment]
@IslandUsurper It isnt quite, was going to review your PR later on.

**Comment by IslandUsurper** [comment]
Yeah, sorry. I got confused about what was happening in the various places.

**Comment by nickpack** [comment]
@chasingmaxwell Working on this now, following ideas in @IslandUsurper's PR but doing a minor refactor. I don't use drush or even do any web work any more, so wont release it until you guys have OK'ed that it works as expected, Will come back shortly with the changes.

**Comment by nickpack** [comment]
@chasingmaxwell @IslandUsurper I've done some minor refactoring, specifically 5e725032

This appears to resolve the case that this ticket was opened for (Thanks for the PR @IslandUsurper - the work I did was based around it). I have noticed an issue with it though, which is not particularly helpful - it seems now drush is actually async, so the grunt task spawn is actually completed before drush has finished running, thus we get no stdin or stderror - I need to look into this some more, and have run out of time for tonight.

**Comment by nickpack** [comment]
Scrap that, fixed it. (aa790d342e50a4c6b0ee37c424dc4c47f6a56470)

@chasingmaxwell @IslandUsurper - Can you give that branch a go and let me know if it works as expected? if all is well, I'll release it to npm.

**Comment by nickpack** [comment]
This is resolved in 0.0.5.

**Comment by chasingmaxwell** [comment]
My implementation of grunt-drush is still functioning properly after the refactor.

**Comment by chasingmaxwell** [comment]
I spoke too soon. I did have an issue with chaining multiple drush targets together in a task list because async wasn't being handled properly. https://github.com/nickpack/grunt-drush/pull/11 should fix it though.
